site_name: Kiss-Headers
site_description: Python package for object oriented headers, HTTP/1.1 style. Parse headers to objects.
site_url: https://ousret.github.io/kiss-headers

theme:
    name: 'material'
    icon:
      logo: material/library
      repo: fontawesome/brands/git-alt
    palette:
      primary: 'teal'
      accent: 'deep orange'

repo_name: ousret/kiss-headers
repo_url: https://github.com/Ousret/kiss-headers/
edit_uri: "https://github.com/Ousret/kiss-headers/tree/master/docs"

nav:
  - Introduction: 'index.md'
  - The Theory: 'the-theory.md'
  - Usages :
    - Quick Start: 'quickstart.md'
    - Advanced Tips:
      - Headers: 'advanced-headers.md'
      - Header: 'advanced-header.md'
      - Polymorphism: 'polymorphism.md'
  - The Builder: 'the-builder.md'
  - Explain Headers: 'explain-headers.md'
  - Email: 'imap.md'
  - Developer Interface:
    - API: 'APIs/functions.md'
    - Models: 'APIs/models.md'
    - Custom Headers: 'APIs/custom-headers.md'
    - Utils: 'APIs/others.md'
  - Contributing: 'contributing.md'

markdown_extensions:
  - extra
  - smarty
  - codehilite
  - admonition
  - mkautodoc

extra_css:
  - custom.css
